data_categories = [
	(1, '', 'Artsitektur Desain'),
	(2, '', 'Buku Hukum'),
	(3, '', 'Buku Import'),
	(4, '', 'Buku Masakan'),
	(5, '', 'Buku Persiapan Ujian'),
	(6, '', 'Buku Remaja dan Anak'),
	(7, '', 'Ekonomi & Bisnis'),
	(8, 1, 'Buku Bangunan'),
	(9, 1, 'Buku Codes Standar'),
	(10, 1, 'Buku Dekorasi Ornamen'),
	(11, 1, 'Buku Desain Dapur'),
	(12, 1, 'Buku Kamar'),
	(13, 2, 'Buku Gender & Hukum'),
	(14, 2, 'Buku Hukum Dagang'),
	(15, 2, 'Buku Hukum Internasional'),
	(16, 2, 'Buku Hukum Perdata'),
	(17, 2, 'Buku Hukum Pidana'),
	(18, 3, 'Agriculture Book Import'),
	(19, 3, 'Art & Novel Import'),
	(20, 3, 'Child & Teenager Book Import'),
	(21, 3, 'Computer Book Import'),
	(22, 4, 'Resep Kue'),
	(23, 4, 'Resep Makanan Bayi & Balita'),
	(24, 4, 'Resep Makanan Diet'),
	(25, 4, 'Resep Masakan'),
	(26, 5, 'Persiapan Tes CPNS'),
	(27, 5, 'Persiapan Tes TOEFL & IELTS'),
	(28, 5, 'Persiapan TPA & Psikotest'),
	(29, 6, 'Buku Aktivitas'),
	(30, 6, 'Buku Cerita Anak'),
	(31, 6, 'Buku Dongeng'),
	(32, 6, 'Buku Dunia Pengetahuan'),
	(33, 7, 'Buku Akuntansi'),
	(34, 7, 'Buku Bisnis'),
	(35, 7, 'Buku Ekonomi'),
	(36, 7, 'Buku Kesekretariatan'),
]